version: '3.8'

services:
  postgresproduct:
    container_name: "postgresproduct"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: product_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgresproductdata:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

  postgresadmin:
    depends_on:
      - postgresproduct
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgresteste@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgresproductdata:

