version: '3.8'

services:
  mysqlproduct:
    container_name: "mysqlproduct"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "product_db"
      DB_PATH_HOST: /tmp/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysqlproductdata:/var/lib/mysql
    networks:
      - mysql-compose-network

  phpmyadmin:
    depends_on:
      - mysqlproduct
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysqlproduct
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-compose-network

  adminerproduct:
    container_name: "adminerproduct"
    image: adminer
    restart: always
    depends_on: 
      - mysqlproduct
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  mysqlproductdata:

