version: "3.8"

services:
  opensearchproduct1:
    image: opensearchproject/opensearch:latest
    container_name: opensearchproduct1
    environment:
      - cluster.name=opensearchcluster
      - node.name=opensearchproduct1
      - discovery.seed_hosts=opensearchproduct1,opensearchproduct2
      - cluster.initial_cluster_manager_nodes=opensearchproduct1,opensearchproduct2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=!Open$e@rch15
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearchproductdata1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-compose-network

  opensearchproduct2:
    image: opensearchproject/opensearch:latest
    container_name: opensearchproduct2
    environment:
      - cluster.name=opensearchcluster
      - node.name=opensearchproduct2
      - discovery.seed_hosts=opensearchproduct1,opensearchproduct2
      - cluster.initial_cluster_manager_nodes=opensearchproduct1,opensearchproduct2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=!Open$e@rch15
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearchproductdata2:/usr/share/opensearch/data
    networks:
      - opensearch-compose-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearchproduct1:9200", "http://opensearchproduct2:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-compose-network

volumes:
  opensearchproductdata1:
  opensearchproductdata2:

networks:
  opensearch-compose-network:
  
